name: Build WebAssembly

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.5"

      - name: Navigate to source directory
        run: cd test/src/monkey

      - name: Build WebAssembly
        working-directory: test/src/monkey
        run: GOOS=js GOARCH=wasm go build -tags "js,wasm" -o interpreter.wasm ./wasm_main.go

      - name: Copy wasm_exec.js
        working-directory: test/src/monkey
        run: cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            test/src/monkey/interpreter.wasm
            test/src/monkey/wasm_exec.js
          tag_name: wasm-v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
